version: '3'

services:
  hey-car-app-container:
    image: exchange-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/exchange-app
    ports:
      - "8081:8080"
