version: '3'

services:
  hey-car-app-container:
    image: solactive-ticks-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/solactive-ticks-app
    ports:
      - "8081:8080"
