db.host: localhost
db.name: miner
db.username: postgres
db.password: password

spring:
  application.name: hubspot-service
  profiles.active: default

  datasource:
    url: "jdbc:postgresql://${db.host}:5432/${db.name}"
    platform: postgresql
    driverClassName: org.postgresql.Driver
    username: ${db.username}
    password: ${db.password}
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    ignore-missing-migrations: true
    out-of-order: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      enabled: true

file.upload-dir: /Users/sivasyambuddana/